feat: Take IdentifierProvider into use for equality determination in list-box
vaadin/vaadin-flow-components pull request #246
Opened 2020-10-14 13:03 UTC by taefi

Fix: #225 
Fix: #227

2020-10-15 06:15 UTC, mshabarov requested changes

2020-10-15 06:15 UTC, mshabarov commented on vaadin-list-box-flow-parent/vaadin-list-box-flow/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java
> +        listBox.setValue(new CustomItem(2L));
What if we set `new CustomItem(2L, "Second")` to the list box? Or even `new CustomItem("Second")`? Should we test this case also?

2020-10-15 06:15 UTC, mshabarov commented on vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/MultiSelectListBox.java
> +    protected boolean valueEquals(Set<T> value1, Set<T> value2) {
Same comment about javadoc here

2020-10-15 06:15 UTC, mshabarov commented on vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewIT.java
> +    public void setIdentifierProvider_forMultiSelectListBox_shouldSelectCorrectItems_dueToIdentifier() {
Rework the naming https://sites.google.com/a/vaadin.com/fw-flow-team-s-wiki/contributing-code/flow-way-of-devloping

2020-10-15 06:15 UTC, mshabarov commented on vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxDataViewIT.java
> +    public void setIdentifierProvider_forListBox_shouldSelectCorrectItem_dueToIdentifier() {
Rework the naming https://sites.google.com/a/vaadin.com/fw-flow-team-s-wiki/contributing-code/flow-way-of-devloping

2020-10-15 14:00 UTC, taefi commented on vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBox.java
> +    protected boolean valueEquals(T value1, T value2) {
Agree! Done.

2020-10-16 06:11 UTC, mshabarov requested changes

2020-10-16 06:12 UTC, mshabarov commented
A couple of typos, but LGTM

2020-10-16 10:05 UTC, mshabarov approved these changes

2020-10-16 10:08 UTC, merged