test: fix compilation in Java11 by adding Twitter's ObjectSizeCalculator
vaadin/vaadin-flow-components pull request #316
Opened 2020-10-26 14:01 UTC by manolo

Fixes: #315

2020-10-26 14:12 UTC, fluorumlabs requested changes

2020-10-26 14:12 UTC, fluorumlabs commented on vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/data/performance/ObjectSizeCalculator.java
> +// Copyright 2011 Twitter, Inc.
This file looks like an exact copy of `jdk.nashorn.internal.ir.debug.ObjectSizeCalculator`, originally licensed under GPL2 by Oracle. Even if it's a derivative, GPL2 prohibits license change.

2020-10-27 08:46 UTC, fluorumlabs approved these changes

2020-10-27 09:55 UTC, merged

2021-10-18 11:48 UTC, ZheSun88 commented
i will do the pick manually.